### ISSUE TITLE
Cannot pay back

### ISSUE THREAD

**Issue by 3xtr00verman** [ebtc-protocol/ebtc-bugs-and-issues#6]
**Describe the bug**
Cannot pay back the borrowed eBTC, regardless of intended payment amount.

**To Reproduce**
1. Go to 'POSITIONS'
2. Click on 'MANAGE' under 'OPEN POSITIONS'
3. Scroll down to 'DEBT' and the click on 'PAY BACK' and enter amount to pay back and click on 'REPAY'. Confirm.
4. See error : Execution reverted: BorrowerOperations: Cdp's net stEth balance must not fall below minimum

**Expected behavior**
Pay back eBtc loan

**Screenshots**

![eBTC error](https://github.com/ebtc-protocol/ebtc-bugs-and-issues/assets/75982701/f525519d-8084-411d-b406-72c9908bf934)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Brave]
 - Version [[Version 1.59.124]

**Comment by mrbasado** [comment]
Heyo @3xtr00verman Thanks for the report. You can close your position by clicking on the down arrow then clicking the close button just above the 'Repay' Button. Also if you put in the exact amount the text will change to: 
![Screen Shot 2023-11-06 at 2 16 40 PM](https://github.com/ebtc-protocol/ebtc-bugs-and-issues/assets/95517127/17f5fbb7-c117-4dce-a3df-8e4b946e5752)

We are looking into multiple other solutions to make this process more clear. Let me know if this addresses your issue and thank you again for the report.

edit* I believe you got that error because lowering your debt would make your CR too low. If you send the Cdp Id (right above the Debt tab) i can look into more closely

**Comment by mrbasado** [comment]
@3xtr00verman we have added a max button for the Debt->Pay back input that should make it easy to close without the dropdown. Thank you for your feedback!
